// <auto-generated />
using Hospital.Auth.Core.Implementation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hospital.Auth.Core.Migrations
{
    [DbContext(typeof(AuthDBContext))]
    [Migration("20260307115103_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hospital.Auth.Core.InternalModels.User", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.Property<bool>("Admin")
                        .HasColumnType("boolean")
                        .HasColumnName("admin");

                    b.Property<bool>("KitchenUser")
                        .HasColumnType("boolean")
                        .HasColumnName("kitchen_user");

                    b.Property<bool>("MealsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("meals_admin");

                    b.Property<bool>("MealsUser")
                        .HasColumnType("boolean")
                        .HasColumnName("meals_user");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<bool>("PatientAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("patient_admin");

                    b.HasKey("Username");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("users", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
