// <auto-generated />
using System;
using Hospital.Kitchen.Core.Implementation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hospital.Kitchen.Core.Migrations
{
    [DbContext(typeof(KitchenDBContext))]
    [Migration("20260307142456_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hospital.Kitchen.Core.InternalModels.Tray", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LastUpdateDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date_time");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("middle_name");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("patient_id");

                    b.Property<Guid>("PatientMealRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_meal_request_id");

                    b.Property<DateTime>("ReceivedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_date_time");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("recipe_name");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("FirstName");

                    b.HasIndex("LastName");

                    b.HasIndex("MiddleName");

                    b.HasIndex("PatientMealRequestId")
                        .IsUnique();

                    b.ToTable("trays", "dbo");
                });

            modelBuilder.Entity("Hospital.Kitchen.Core.InternalModels.TrayIngredient", b =>
                {
                    b.Property<Guid>("TrayId")
                        .HasColumnType("uuid")
                        .HasColumnName("tray_id");

                    b.Property<string>("IngredientName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("ingredient_name");

                    b.Property<decimal>("Qty")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("qty");

                    b.Property<string>("Unit")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("unit");

                    b.HasKey("TrayId", "IngredientName");

                    b.ToTable("tray_ingredients", "dbo");
                });

            modelBuilder.Entity("Hospital.Kitchen.Core.InternalModels.TrayStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid>("TrayId")
                        .HasColumnType("uuid")
                        .HasColumnName("tray_id");

                    b.HasKey("Id");

                    b.HasIndex("TrayId");

                    b.ToTable("tray_status_history", "dbo");
                });

            modelBuilder.Entity("Hospital.Kitchen.Core.InternalModels.TrayIngredient", b =>
                {
                    b.HasOne("Hospital.Kitchen.Core.InternalModels.Tray", null)
                        .WithMany("TrayIngredients")
                        .HasForeignKey("TrayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hospital.Kitchen.Core.InternalModels.TrayStatusHistory", b =>
                {
                    b.HasOne("Hospital.Kitchen.Core.InternalModels.Tray", null)
                        .WithMany()
                        .HasForeignKey("TrayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hospital.Kitchen.Core.InternalModels.Tray", b =>
                {
                    b.Navigation("TrayIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
