// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Hospital.Patient.Core.Implementation;

#nullable disable

namespace Hospital.Patient.Core.Migrations
{
    [DbContext(typeof(PatientDBContext))]
    [Migration("20260306025751_InitialPatientTables")]
    partial class InitialPatientTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hospital.Patient.Core.InternalModels.Allergies", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("allergies", "dbo");
                });

            modelBuilder.Entity("Hospital.Patient.Core.InternalModels.ClinicalStates", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("clinical_states", "dbo");
                });

            modelBuilder.Entity("Hospital.Patient.Core.InternalModels.DietTypes", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("diet_types", "dbo");
                });

            modelBuilder.Entity("Hospital.Patient.Core.InternalModels.Patient", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("id");

                    b.Property<string>("DietTypeId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("diet_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.HasIndex("DietTypeId");

                    b.ToTable("patients", "dbo");
                });

            modelBuilder.Entity("Hospital.Patient.Core.InternalModels.PatientAllergies", b =>
                {
                    b.Property<string>("PatientId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("patient_id");

                    b.Property<string>("AllergyId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("allergy_id");

                    b.HasKey("PatientId", "AllergyId");

                    b.HasIndex("AllergyId");

                    b.ToTable("patient_allergies", "dbo");
                });

            modelBuilder.Entity("Hospital.Patient.Core.InternalModels.PatientClinicalStates", b =>
                {
                    b.Property<string>("PatientId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("patient_id");

                    b.Property<string>("ClinicalStateId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("clinical_state_id");

                    b.HasKey("PatientId", "ClinicalStateId");

                    b.HasIndex("ClinicalStateId");

                    b.ToTable("patient_clinical_states", "dbo");
                });

            modelBuilder.Entity("Hospital.Patient.Core.InternalModels.Patient", b =>
                {
                    b.HasOne("Hospital.Patient.Core.InternalModels.DietTypes", null)
                        .WithMany()
                        .HasForeignKey("DietTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hospital.Patient.Core.InternalModels.PatientAllergies", b =>
                {
                    b.HasOne("Hospital.Patient.Core.InternalModels.Allergies", null)
                        .WithMany()
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hospital.Patient.Core.InternalModels.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hospital.Patient.Core.InternalModels.PatientClinicalStates", b =>
                {
                    b.HasOne("Hospital.Patient.Core.InternalModels.ClinicalStates", null)
                        .WithMany()
                        .HasForeignKey("ClinicalStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hospital.Patient.Core.InternalModels.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
